export const ERROR_MESSAGES = {
  F1: `The plugin couldn't load correctly.`,
  F2: `There was an error generating the components.`,
  F3: `There was an error generating the components.`,
  F4: '',
  F5: `There was an error creating a new document.`,
  F6: `There was an error creating a new document.`,
  F7: `There was an error generating the frame data.`,
  F8: `There was an error generating the frame data.`,
  F9: `There was an error generating an instance.`,
  F10: `There was an error generating an instance.`,
  F11: `There was an error generating a Header instance.`,
  F12: `There was an error generating a Paragraph instance.`,
  F13: `There was an error generating a Quote instance.`,
  F14: `There was an error generating a Display Frame instance.`,
  F15: `There was an error generating a Dos and dont's instance.`,
  F16: `There was an error generating a List instance.`,
  F17: `There was an error generating a Table instance.`,
  F18: `There was an error generating an Alert instance.`,
  F19: `There was an error generating a Code block instance.`,
  F20: `There was an error generating a Divider instance.`,
  F21: `There was an error generating a Component Doc instance.`,
  F22: `There was an error generating the page data from the Figma content.`,
  F23: `There was an error generating the page data from the Figma content.`,
  F24: `There was an error generating the page data from a header block.`,
  F25: `There was an error generating the page data from a paragraph block.`,
  F26: `There was an error generating the page data from a quote block.`,
  F27: `There was an error generating the page data from a list block.`,
  F28: `There was an error generating the page data from an alert block.`,
  F29: `There was an error generating the page data from a code block.`,
  F30: `There was an error generating the page data from a divider block.`,
  F31: `There was an error hydrating and generating the page data from a dos and dont's block.`,
  F32: `There was an error hydrating and generating the page data from a component doc block.`,
  F33: `There was an error generating the page data from the Figma content.`,
  F34: `There was an error generating the page data from the Figma content.`,
  F35: `There was an error generating the page data from a display frame block.`,
  F36: `There was an error hydrating and generating the page data from a display frame block.`,
  F37: `There was an error generating the page data from a dos and dont's block.`,
  F38: `There was an error generating the page data from a table block.`,
  F39: `There was an error generating the page data from a component doc block.`,
  F40: `There was an error generating the page data from a component doc block.`,
  F41: `There was an error generating the page data from a component doc block.`,
  F42: `There was an error generating the page data from a component doc block.`,
  F43: `There was an error generating the page data from a component doc block.`,
  F44: `There was an error generating the page data from a component doc block.`,
  F45: `There was an error generating the page data from a component doc block.`,
  F46: `There was an error generating the page data from a component doc block.`,
  F47: `There easy component docs were deleted, please restart the plugin to regenerate them`,
  E1: `The export took to long, please try again.`,

};
